language: python

#cache: pip
#
python:
#  - "2.6"
#  - "2.7"
#  - "3.2"
#  - "3.3"
#  - "3.4"
  - "3.5"
#  - "3.5-dev" # 3.5 development branch
#  - "3.6"
#  - "3.6-dev" # 3.6 development branch
#  - "3.7-dev" # 3.7 development branch
#  - "nightly" # currently points to 3.7-dev
# PyPy versions
#  - "pypy"  # PyPy2 2.5.0
#  - "pypy3" # Pypy3 2.4.0
#  - "pypy-5.3.1"
#

env:
  global:
  - GH_REF: git@github.com:smarie/python-object-as-daemon.git

before_install:
  - sudo apt-get install pandoc

install:
  - pip install -r requirements-setup.txt
  - pip install -r requirements-test.txt
  - pip install -r requirements-doc.txt
  - pip install codecov  # https://github.com/codecov/example-python
# - pip install coveralls is an alternative to codecov
  - pip install .

script:
#  - coverage run tests.py
  - pytest --cov-report term-missing --cov=./pyoad -v pyoad/tests/

after_success:
# ***reporting***
  - codecov
# - coveralls is an alternative to codecov
# ***documentation***
  - mkdocs build
#  - mkdocs gh-deploy requires special care :
  # ---grant the possibility to push on the repo---
  - openssl aes-256-cbc -K $encrypted_60e2bdb32373_key -iv $encrypted_60e2bdb32373_iv -in github_travis_rsa.enc -out github_travis_rsa -d
  - chmod 600 github_travis_rsa
  - eval `ssh-agent -s`  # launch the authentication agent
  - ssh-add github_travis_rsa  # register the key
  - git config user.name "Automatic Publish"
  - git config user.email "sylvain.marie@schneider-electric.com"
  - git remote add gh-token "${GH_REF}";
  - git fetch gh-token && git fetch gh-token gh-pages:gh-pages;
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then echo "Pushing to github"; PYTHONPATH=pyoad/ mkdocs gh-deploy -v --clean --remote-name gh-token; git push gh-token gh-pages; fi;

#matrix:
#    fast_finish: true

notifications:
  email:
    on_success: never  # options: [always|never|change] default: always