language: python

#cache: pip

python:
#  - "2.6"
#  - "2.7"
#  - "3.2"
#  - "3.3"
#  - "3.4"
  - "3.5"
#  - "3.5-dev" # 3.5 development branch
  - "3.6"
#  - "3.6-dev" # 3.6 development branch
#  - "3.7-dev" # 3.7 development branch
#  - "nightly" # currently points to 3.7-dev
# PyPy versions
#  - "pypy"  # PyPy2 2.5.0
#  - "pypy3" # Pypy3 2.4.0
#  - "pypy-5.3.1"
#

env:
  global:
  - GH_REF: git@github.com:smarie/python-object-as-daemon.git

before_install:
  - sudo apt-get install pandoc
  - sudo apt-get install ant

install:
  - pip install -r ci_tools/requirements-setup.txt
  - pip install -r ci_tools/requirements-test.txt
  - pip install -r ci_tools/requirements-report.txt
  - pip install -r ci_tools/requirements-doc.txt
  - pip install codecov    # https://github.com/codecov/example-python. This is specific to travis integration
# - pip install coveralls  # this is an alternative to codecov
  - pip install .

script:
#  - coverage run tests.py
  - pytest --cov-report term-missing  --junitxml=junit.xml --cov=./pyoad -v pyoad/tests/

after_success:
# ***reporting***
#  - junit2html junit.xml testrun.html  output is really not nice
  - ant -f ci_tools/generate-junit-html.xml  # generates the html for the test results
  - python ci_tools/generate-junit-badge.py  # generates the badge for the test results
  - codecov
  - pylint pyoad  # note that at the moment the report is simply lost, we dont transform the result into anything
# ***documentation***
  - mkdocs build -f ci_tools/mkdocs.yml
  - mv reports/junit site/
  # mkdocs gh-deploy requires special care :
  # ---grant the possibility to push on the repo---
  - openssl aes-256-cbc -K $encrypted_60e2bdb32373_key -iv $encrypted_60e2bdb32373_iv -in ci_tools/github_travis_rsa_pyoad.enc -out ci_tools/github_travis_rsa_pyoad -d
  - chmod 600 ci_tools/github_travis_rsa_pyoad
  - eval `ssh-agent -s`  # launch the authentication agent
  - ssh-add ci_tools/github_travis_rsa_pyoad  # register the key
  - git config user.name "Automatic Publish"
  - git config user.email "sylvain.marie@schneider-electric.com"
  - git remote add gh-token "${GH_REF}";
  - git fetch gh-token && git fetch gh-token gh-pages:gh-pages;
  # push but only if this is not a build triggered by a pull request
  # note: here we use the --dirty flag so that mkdocs does not clean the additional reports that we copied in the site
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then echo "Pushing to github"; PYTHONPATH=pyoad/ mkdocs gh-deploy -v --dirty -f ci_tools/mkdocs.yml --remote-name gh-token; git push gh-token gh-pages; fi;

deploy:
  provider: pypi
  user: "smarie"
  password:
    secure: "rhZ0DDTlGeRiXeotIFr2VvC9NaoobbmNEXY6c9sRYu60Ctn8kBWVUIqVXUYrlRLeGNlHb/oFdXxEDNsZrZdvWEW92ulaCWmzsqbjBxouSsz6TFkHD0sqHkbxx6j0um9OcTh5qUKjTKM6epdem6XSVdT+PRPNjaGTJAZSuihMxmI1OFntk2OEwLW34ZWH6/H5wEChDTU3BlfaoaklU0c+fCYGUx46+M0toqbElLtwx0lpu6ARXfptLUxGT+h/VLIvB7lULwKTCoAoUflVzFKZ2DxGpi7c6Er6CHO/9DBdJna7K76VfN/G+dg/Ddos1NtPoRX9vkLelLlYYa/4YGav6D0BNC7n0t42FSzIsGCxexYEJTvk1ZyZXiqdp/4eoGbvXUfrnotKovN0LQuiqqI5qsh3NH1qdNjyQOrms6QpWQSXQvnIkRM9hnArCZJ04GuhL3fdGhSnAWhV9XIO3vqiILNxNOQliVzFfdQKfTemI08fTLAJ5V8ZRtwRKQqV60WZ37kyqkka6/hYMR/8ysUz2xPNLJ53d+pAEXsn/6n43M+GTaJ+8a81cFT6rsGANH2BN3mXxP9AOJZMyqDAoMp9hdDuNmRevxp1qrwTNzl7RXwTcKNWua+Srhkr3VSWI7PwWYsnZ2/FSoI3MMUuDFyTD3s4plu4/0gsdwlJPSuAEmw="
  on:
    tags: true
  server: https://test.pypi.org/legacy/
  distributions: "bdist_wheel"

matrix:
    fast_finish: true

notifications:
  email:
    on_success: never  # options: [always|never|change] default: always
